"use client";

import { FormEvent, useMemo, useState } from "react";
import { createJob, type FactoryJob, type FactoryOperation, runOperation } from "./factory-api";
import { Heading, Icon, Panel, Pill, Toggle } from "./Primitives";

type PendingAction = { title: string; detail: string; run: () => Promise<FactoryJob> };
type Notice = { tone: "success" | "error"; text: string };

const capabilityNotes = [
  ["bookings", "Bookings", "Collect dates and guest details for owner review."],
  ["handoff", "Human handoff", "Offer a warm transfer when policy requires it."],
  ["after-hours", "After-hours capture", "Capture a callback request outside support hours."],
] as const;

const steps = [
  ["intake", "1", "Intake"],
  ["inspect", "2", "Inspect"],
  ["knowledge", "3", "Knowledge review"],
  ["plan", "4", "Plan review"],
  ["handoff", "5", "PR handoff"],
] as const;

function nextStep(job: FactoryJob | null) {
  if (!job) return "intake";
  if (job.state === "draft") return "inspect";
  if (job.state === "inspected") return "inspect";
  if (job.state === "knowledge_review_required") return "knowledge";
  if (job.state === "plan_review_required") return "plan";
  return "handoff";
}

function timelineFor(job: FactoryJob | null) {
  if (!job) return [{ label: "Waiting for an intake job", detail: "No server job has been created", tone: "pending" }];
  const timeline = [{ label: "Job created", detail: `Server job ${job.job_id}`, tone: "done" }];
  if (job.state !== "draft") timeline.push({ label: "Inspection returned", detail: `Server stage: ${job.state === "inspected" ? "inspected" : "inspection complete"}`, tone: "done" });
  if (job.state === "knowledge_review_required") timeline.push({ label: "Knowledge review required", detail: "Approve the server-returned knowledge digest", tone: "current" });
  if (job.state === "plan_review_required") timeline.push({ label: "Knowledge review returned", detail: "Server advanced to plan review", tone: "done" }, { label: "Plan review required", detail: "Approve the server-returned plan digest", tone: "current" });
  if (["approved_for_generation", "generated", "verified", "pr_ready"].includes(job.state)) timeline.push({ label: "Plan review returned", detail: `Server stage: ${job.state}`, tone: "done" });
  if (["generated", "verified", "pr_ready"].includes(job.state)) timeline.push({ label: "Generation returned", detail: "Review artifact generated by the server", tone: "done" });
  if (["verified", "pr_ready"].includes(job.state)) timeline.push({ label: "Verification returned", detail: "Server verification completed", tone: "done" });
  if (job.state === "pr_ready") timeline.push({ label: "PR handoff returned", detail: "Review-ready handoff recorded by the server", tone: "done" });
  if (job.state === "blocked") timeline.push({ label: "Factory blocked", detail: "The server refused to advance this job", tone: "error" });
  return timeline;
}

export default function FactoryConsole() {
  const [job, setJob] = useState<FactoryJob | null>(null);
  const [activeStep, setActiveStep] = useState<(typeof steps)[number][0]>("intake");
  const [capabilities, setCapabilities] = useState<Record<string, boolean>>({});
  const [form, setForm] = useState({ company_name: "", industry: "Hospitality", purpose: "", primary_contact: "", supported_languages: "en" });
  const [pending, setPending] = useState<PendingAction | null>(null);
  const [notice, setNotice] = useState<Notice | null>(null);
  const timeline = timelineFor(job);
  const digest = job?.review?.digest ?? null;
  const enabledCapabilities = useMemo(() => capabilityNotes.filter(([id]) => capabilities[id]).map(([, label]) => label), [capabilities]);

  function confirm(title: string, detail: string, run: () => Promise<FactoryJob>) {
    setNotice(null);
    setPending({ title, detail, run });
  }

  async function execute() {
    if (!pending) return;
    const action = pending;
    setPending(null);
    try {
      const updated = await action.run();
      setJob(updated);
      setActiveStep(nextStep(updated));
      setNotice({ tone: "success", text: `${action.title} returned server stage “${updated.state}”.` });
    } catch (error) {
      setNotice({ tone: "error", text: error instanceof Error ? error.message : "Factory request failed. No local state was changed." });
    }
  }

  function submitIntake(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const payload = { ...form, supported_languages: form.supported_languages.split(",").map((value) => value.trim()).filter(Boolean) };
    confirm("Create factory job", "The server will validate this exact non-secret intake contract and return the authoritative job ID.", async () => createJob(payload));
  }

  function operate(operation: FactoryOperation, title: string, detail: string, operationDigest?: string) {
    if (!job) return;
    confirm(title, detail, () => runOperation(job.job_id, operation, operationDigest));
  }

  return <main className="min-h-screen bg-[#f6f8fb] text-slate-950"><div className="mx-auto max-w-[1480px] px-4 py-5 sm:px-6 lg:px-10 lg:py-8">
    <header className="flex flex-col gap-6 border-b border-slate-200 pb-7 lg:flex-row lg:items-start lg:justify-between"><div className="flex items-start gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-950 text-sm font-bold text-white">F/</div><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold tracking-tight">SmartPBX Factory</p><Pill tone="amber">Owner review</Pill></div><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Review before anything runs.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">A standalone private-origin surface for server-backed factory jobs, digest approvals, and review-ready PR handoff.</p></div></div><div className="flex items-center gap-2 self-start rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-medium text-slate-500 shadow-sm"><span className="h-2 w-2 rounded-full bg-emerald-500" />Private origin configured outside this client</div></header>
    <div className="mt-7 grid gap-8 lg:grid-cols-[minmax(0,1fr)_320px]"><div>
      <nav aria-label="Factory job steps" className="mb-7 overflow-x-auto"><ol className="flex min-w-max items-center gap-2 rounded-xl border border-slate-200 bg-white p-2 shadow-sm">{steps.map(([id, number, label], index) => <li key={id} className="flex items-center gap-2"><button type="button" onClick={() => setActiveStep(id)} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-cyan-500 ${activeStep === id ? "bg-slate-950 text-white" : "text-slate-500 hover:bg-slate-50"}`} aria-current={activeStep === id ? "step" : undefined}><span className={`flex h-5 w-5 items-center justify-center rounded-full text-[10px] ${activeStep === id ? "bg-cyan-400 text-slate-950" : "bg-slate-100"}`}>{number}</span>{label}</button>{index < steps.length - 1 ? <span className="text-slate-300">/</span> : null}</li>)}</ol></nav>
      {notice ? <div role="status" className={`mb-5 rounded-xl border px-4 py-3 text-sm ${notice.tone === "success" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-rose-200 bg-rose-50 text-rose-800"}`}>{notice.text}</div> : null}
      {activeStep === "intake" ? <Panel className="p-5 sm:p-7"><Heading eyebrow="Company intake" title="Create a server-owned factory job." description="Only the backend's non-secret intake fields are accepted. The client does not send URLs, credentials, provider choices, or infrastructure settings." /><form onSubmit={submitIntake} className="grid gap-5 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Company name</span><input required value={form.company_name} onChange={(e) => setForm({ ...form, company_name: e.target.value })} className="factory-field" placeholder="Northstar Hotels" /></label><label><span className="label">Industry</span><input required value={form.industry} onChange={(e) => setForm({ ...form, industry: e.target.value })} className="factory-field" placeholder="Hospitality" /></label><label><span className="label">Supported languages</span><input required value={form.supported_languages} onChange={(e) => setForm({ ...form, supported_languages: e.target.value })} className="factory-field" placeholder="en, ko" /><span className="help">Comma-separated language codes.</span></label><label><span className="label">Primary contact</span><input required value={form.primary_contact} onChange={(e) => setForm({ ...form, primary_contact: e.target.value })} className="factory-field" placeholder="Owner name and email" /></label><label className="sm:col-span-2"><span className="label">Agent purpose</span><textarea required value={form.purpose} onChange={(e) => setForm({ ...form, purpose: e.target.value })} className="factory-field min-h-24 resize-y" placeholder="Answer approved guest questions and collect callback requests." /></label><div className="flex items-center justify-between gap-4 border-t border-slate-100 pt-5 sm:col-span-2"><p className="help">Create opens a deliberate confirmation screen.</p><button type="submit" className="factory-button-primary">Create job <Icon name="arrow" /></button></div></form></Panel> : null}
      {activeStep === "inspect" ? <div className="space-y-6"><Panel className="p-5 sm:p-7"><Heading eyebrow="Server inspection" title="Inspect the submitted job." description="Inspection and planning are server operations. Their returned state is the only source of truth for this console." /><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">Job ID</p><p className="mt-2 break-all font-mono text-sm text-slate-800">{job?.job_id ?? "No job created"}</p><p className="mt-2 text-xs text-slate-500">Current server stage: {job?.state ?? "draft"}</p></div><div className="mt-5 flex flex-wrap gap-2"><button type="button" disabled={!job || job.state !== "draft"} onClick={() => operate("inspect", "Inspect job", "The backend will validate the owner-approved intake and return the next stage.")} className="factory-button-primary">Run inspection <Icon name="arrow" /></button><button type="button" disabled={!job || job.state !== "inspected"} onClick={() => operate("plan", "Prepare factory plan", "The backend will stage the knowledge review and return its exact digest.")} className="factory-button-primary">Prepare plan <Icon name="arrow" /></button></div></Panel><Panel className="p-5 sm:p-7"><Heading eyebrow="Capability notes" title="Keep optional behavior off by default." description="These toggles are a local planning aid only. Factory API v1 rejects unknown capability fields, so no toggle state is sent or represented as approved until the backend contract carries it." />{capabilityNotes.map(([id, label, description]) => <Toggle key={id} label={label} description={description} checked={Boolean(capabilities[id])} onChange={() => setCapabilities((current) => ({ ...current, [id]: !current[id] }))} />)}{enabledCapabilities.length ? <p className="mt-4 rounded-lg bg-amber-50 px-3 py-2 text-xs leading-5 text-amber-800">Draft-only selection: {enabledCapabilities.join(", ")}. Not submitted to the factory job.</p> : null}</Panel></div> : null}
      {activeStep === "knowledge" ? <Panel className="p-5 sm:p-7"><Heading eyebrow="Knowledge review" title="Approve the server-returned knowledge artifact." description="The digest below is returned by GET/POST /v1/jobs. Nothing is invented in the browser, and approval sends the exact digest back to the server." /><ReviewCard review={job?.review} kind="knowledge" /><button type="button" disabled={!job || job.review?.status !== "knowledge_review_required"} onClick={() => operate("approve-knowledge", "Approve knowledge review", "This sends the exact server-returned knowledge digest for owner confirmation.", digest ?? undefined)} className="factory-button-primary mt-5">Approve knowledge digest <Icon name="check" /></button></Panel> : null}
      {activeStep === "plan" ? <Panel className="p-5 sm:p-7"><Heading eyebrow="Plan review" title="Approve the server-returned plan artifact." description="Knowledge approval must already be returned by the server. This separate confirmation is bound to the exact plan digest." /><ReviewCard review={job?.review} kind="plan" /><button type="button" disabled={!job || job.review?.status !== "plan_review_required"} onClick={() => operate("approve-plan", "Approve plan review", "This sends the exact server-returned plan digest for owner confirmation.", digest ?? undefined)} className="factory-button-primary mt-5">Approve plan digest <Icon name="check" /></button></Panel> : null}
      {activeStep === "handoff" ? <div className="space-y-6"><Panel className="p-5 sm:p-7"><Heading eyebrow="PR handoff" title="Advance only through returned server stages." description="Generation, verification, and PR handoff are review operations. This client does not infer IDs, digests, PR links, or deployment readiness." /><div className="grid gap-4 sm:grid-cols-2"><div className="metric"><span>Job ID</span><strong>{job?.job_id ?? "—"}</strong></div><div className="metric"><span>Server stage</span><strong>{job?.state ?? "draft"}</strong></div></div><div className="mt-5 flex flex-wrap gap-2"><button type="button" disabled={!job || job.state !== "approved_for_generation"} onClick={() => operate("generate", "Generate review artifact", "The backend will generate only after both digest approvals.")} className="factory-button-primary">Generate</button><button type="button" disabled={!job || job.state !== "generated"} onClick={() => operate("verify", "Verify review artifact", "The backend will run its provenance and readiness checks.")} className="factory-button-primary">Verify</button><button type="button" disabled={!job || job.state !== "verified"} onClick={() => operate("open-pr", "Open PR handoff", "The backend will create the review-ready handoff. Deployment is not part of this operation.")} className="factory-button-primary"><Icon name="external" /> Open PR handoff</button></div></Panel><Panel className="border-amber-200 bg-amber-50/50 p-5 sm:p-7"><div className="flex items-start gap-3"><div className="rounded-lg bg-amber-100 p-2 text-amber-700"><Icon name="lock" /></div><div><h2 className="text-sm font-semibold text-amber-950">Deployment is absent from the contract</h2><p className="mt-1 text-sm leading-6 text-amber-900/70">Provisioning, DNS, provider setup, and production rollout are not executable controls in this console.</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled className="factory-button-disabled">Deploy agent</button><button type="button" disabled className="factory-button-disabled">Provision infrastructure</button><button type="button" disabled className="factory-button-disabled">Configure DNS</button></div></div></div></Panel></div> : null}
    </div><aside className="space-y-6 lg:pt-[69px]"><Panel className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Server timeline</h2><Pill tone="blue">Read-only view</Pill></div><p className="mt-1 text-xs text-slate-500">Derived from the latest returned job state</p></div><ol className="space-y-0 px-5 py-2">{timeline.map((event) => <li key={`${event.label}-${event.detail}`} className="relative flex gap-3 py-4"><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${event.tone === "done" ? "bg-emerald-500" : event.tone === "current" ? "bg-cyan-500" : event.tone === "error" ? "bg-rose-500" : "bg-slate-300"}`} /><div><p className="text-xs font-semibold text-slate-800">{event.label}</p><p className="mt-1 text-xs leading-5 text-slate-500">{event.detail}</p></div></li>)}</ol></Panel><Panel className="p-5"><div className="flex items-start gap-3"><div className="rounded-lg bg-slate-100 p-2 text-slate-500"><Icon name="lock" /></div><div><h2 className="text-sm font-semibold">Boundary check</h2><p className="mt-1 text-xs leading-5 text-slate-500">No credentials, arbitrary URL fetches, client-side access claims, provisioning, or deployment controls.</p></div></div></Panel></aside></div>
    </div>{pending ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 px-4 backdrop-blur-[2px]"><div role="dialog" aria-modal="true" aria-labelledby="confirmation-title" className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start gap-3"><div className="rounded-lg bg-cyan-50 p-2 text-cyan-700"><Icon name="lock" /></div><div><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-cyan-700">Owner confirmation</p><h2 id="confirmation-title" className="mt-1 text-xl font-semibold tracking-tight">{pending.title}?</h2></div></div><p className="mt-4 text-sm leading-6 text-slate-600">{pending.detail}</p><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setPending(null)} className="factory-button-secondary">Cancel</button><button type="button" onClick={execute} className="factory-button-primary">Confirm request <Icon name="check" /></button></div></div></div> : null}</main>;
}

function ReviewCard({ review, kind }: { review: FactoryJob["review"] | undefined; kind: "knowledge" | "plan" }) {
  const expected = kind === "knowledge" ? "knowledge_review_required" : "plan_review_required";
  return <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between gap-4"><span className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">{kind} digest</span><Pill tone={review?.status === expected ? "amber" : "neutral"}>{review?.status === expected ? "Awaiting approval" : "Not returned"}</Pill></div><p className="mt-3 break-all font-mono text-sm text-slate-800">{review?.status === expected ? review.digest : "No server digest available"}</p><p className="mt-2 text-xs leading-5 text-slate-500">The value is displayed from the latest server response and is never generated locally.</p></div>;
}
