"""Render the non-secret, backend-gated website demo card contract."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from .model import AgentManifest
from .resources import DerivedResources


_BACKEND_ARTIFACT_DIGEST = re.compile(r"^[0-9a-f]{64}$")
_BACKEND_BRANCH_SHA = re.compile(r"^[0-9a-f]{40}$")
_SUPPORTED_LANGUAGES = frozenset(("en", "ar", "ru", "si"))
_DISALLOWED_VALUE = re.compile(r"(?:wss://|smartpbx-[a-z0-9-]+\.taskforceai\.tech)", re.IGNORECASE)
_DISALLOWED_FIELD = re.compile(r"(?:token|secret|credential|password|api[_-]?key|backendhost|demohost|wss|host|url)", re.IGNORECASE)
_TOKEN_URL = "https://hattonhills.taskforceai.tech/api/voice-token"
_IMPORT = "import { SMARTPBX_AGENT_CARDS } from '../../data/smartpbx-agents.generated';\n"
_ACTIVE_FILTER = 'SMARTPBX_AGENT_CARDS.filter((card) => card.releaseState === "active")'


@dataclass(frozen=True)
class WebsiteDependency:
    """Immutable backend inputs that gate a review-only website artifact."""

    backend_artifact_digest: str
    backend_branch_sha: str
    release_order: tuple[str, str] = ("backend", "website")


@dataclass(frozen=True)
class WebsiteRenderReport:
    dependency: WebsiteDependency
    card_ids: tuple[str, ...]
    output_paths: tuple[Path, ...]


def _validate_dependency(*, backend_artifact_digest: str, backend_branch_sha: str) -> WebsiteDependency:
    if not _BACKEND_ARTIFACT_DIGEST.fullmatch(backend_artifact_digest):
        raise ValueError("backend_artifact_digest must be a lowercase SHA-256 digest")
    if not _BACKEND_BRANCH_SHA.fullmatch(backend_branch_sha):
        raise ValueError("backend_branch_sha must be a full lowercase Git SHA")
    return WebsiteDependency(
        backend_artifact_digest=backend_artifact_digest,
        backend_branch_sha=backend_branch_sha,
    )


def _website_languages(manifest: AgentManifest) -> tuple[str, ...]:
    declared = manifest.website_demo.supported_languages or tuple(language.code for language in manifest.languages)
    languages = tuple(dict.fromkeys(language.split("-", 1)[0].lower() for language in declared))
    if not languages or any(language not in _SUPPORTED_LANGUAGES for language in languages):
        raise ValueError("website demo languages must be supported public language values")
    return languages


def _assert_public_value(value: str, *, field: str) -> str:
    if not value.strip():
        raise ValueError(f"website card field must not be empty: {field}")
    if _DISALLOWED_VALUE.search(value):
        raise ValueError(f"website card field contains a non-public endpoint: {field}")
    return value.strip()


def _card(manifest: AgentManifest, resources: DerivedResources) -> dict[str, object]:
    if resources.slug != manifest.slug:
        raise ValueError("website resources must belong to the manifest slug")
    if not manifest.website_demo.enabled:
        raise ValueError("website demo is disabled")
    if manifest.website_demo.visibility != "pending":
        raise ValueError("website generation only permits pending cards")

    brand = _assert_public_value(manifest.public_name, field="brand")
    agent_name = _assert_public_value(manifest.agent_name, field="agentName")
    purpose = _assert_public_value(manifest.purpose.rstrip("."), field="description")
    ask_hint = _assert_public_value(
        ", ".join(manifest.allowed_topics) or "approved company information",
        field="askHint",
    )
    return {
        "id": manifest.slug,
        "releaseState": "pending",
        "brand": brand,
        "agentName": agent_name,
        "role": "Information Assistant",
        "location": "Online",
        "description": f"{purpose}.",
        "images": [],
        "trainedOn": ["approved company information"],
        "langs": list(_website_languages(manifest)),
        "callLabel": f"Call {brand}",
        "askHint": ask_hint,
        "steps": [
            {
                "bold": "Ask a question.",
                "rest": "Use the approved company information.",
            }
        ],
    }


def _js_literal(value: object) -> str:
    return json.dumps(value, ensure_ascii=True, separators=(",", ": "))


def _render_cards_module(card: dict[str, object], dependency: WebsiteDependency) -> str:
    lines = [
        "// Generated by create-smartpbx-agent. This file contains public review metadata only.",
        "",
        "/** @typedef {'en' | 'ar' | 'ru' | 'si'} SmartPBXLanguage */",
        "/**",
        " * @type {ReadonlyArray<{",
        " *   id: string, releaseState: 'pending' | 'active', brand: string, agentName: string,",
        " *   role: string, location: string, description: string, images: string[], trainedOn: string[],",
        " *   langs: SmartPBXLanguage[], callLabel: string, askHint: string,",
        " *   steps: Array<{bold: string, rest: string}>",
        " * }>} ",
        " */",
        "export const SMARTPBX_AGENT_CARDS = Object.freeze([",
        "  {",
    ]
    for key in (
        "id",
        "releaseState",
        "brand",
        "agentName",
        "role",
        "location",
        "description",
        "images",
        "trainedOn",
        "langs",
        "callLabel",
        "askHint",
        "steps",
    ):
        lines.append(f"    {key}: {_js_literal(card[key])},")
    lines.extend(
        (
            "  },",
            "]);",
            "",
            "export const SMARTPBX_WEBSITE_DEPENDENCY = Object.freeze({",
            f"  backendArtifactDigest: {_js_literal(dependency.backend_artifact_digest)},",
            f"  backendBranchSha: {_js_literal(dependency.backend_branch_sha)},",
            "  releaseOrder: Object.freeze([\"backend\", \"website\"]),",
            "});",
            "",
        )
    )
    return "\n".join(lines)


def _integrate_book_demo(source: str) -> tuple[str, bool]:
    """Add the one-time active-card seam without changing Hatton's issuer flow."""
    if _TOKEN_URL not in source:
        raise ValueError("BookDemo.tsx does not contain the shared HattonHills token issuer")
    if "encodeURIComponent(agent.id)" not in source:
        raise ValueError("BookDemo.tsx does not pass the selected agent to the shared issuer")
    if "params: { agent: agent.id, lang }" not in source:
        raise ValueError("BookDemo.tsx does not preserve agent and language connection parameters")

    changed = False
    if _IMPORT not in source:
        anchor = "import { contactPageSchema } from '../../lib/schema';\n"
        if anchor not in source:
            raise ValueError("BookDemo.tsx import seam is unavailable")
        source = source.replace(anchor, anchor + _IMPORT, 1)
        changed = True

    if _ACTIVE_FILTER not in source:
        marker = "const AGENTS: Agent[] = ["
        if marker not in source:
            raise ValueError("BookDemo.tsx agent list seam is unavailable")
        source = source.replace(marker, "const STATIC_AGENTS: Agent[] = [", 1)
        ending = "\n];\n\nconst langMeta"
        replacement = (
            "\n];\n\n"
            "const AGENTS: Agent[] = [\n"
            "  ...STATIC_AGENTS,\n"
            f"  ...{_ACTIVE_FILTER},\n"
            "];\n\n"
            "const langMeta"
        )
        if ending not in source:
            raise ValueError("BookDemo.tsx agent list closing seam is unavailable")
        source = source.replace(ending, replacement, 1)
        changed = True
    return source, changed


def _validator_source() -> str:
    return """import { readFileSync } from \"node:fs\";
import { SMARTPBX_AGENT_CARDS } from \"../data/smartpbx-agents.generated.mjs\";

const SUPPORTED_LANGUAGES = new Set([\"en\", \"ar\", \"ru\", \"si\"]);
const RESERVED_FIELD = /(?:token|secret|credential|password|api[_-]?key|backendhost|demohost|wss|host|url)/i;
const DISALLOWED_VALUE = /(?:wss:\\/\\/|smartpbx-[a-z0-9-]+\\.taskforceai\\.tech)/i;
const DISPLAY_FIELDS = [\"brand\", \"agentName\", \"role\", \"location\", \"description\", \"callLabel\", \"askHint\"];

function assert(condition, message) {
  if (!condition) throw new Error(`smartpbx card contract: ${message}`);
}

function assertPublic(value, path = \"card\") {
  if (typeof value === \"string\") {
    assert(!DISALLOWED_VALUE.test(value), `${path} contains a non-public endpoint`);
    return;
  }
  if (Array.isArray(value)) {
    value.forEach((item, index) => assertPublic(item, `${path}[${index}]`));
    return;
  }
  if (value && typeof value === \"object\") {
    Object.entries(value).forEach(([key, item]) => {
      assert(!RESERVED_FIELD.test(key), `${path}.${key} is not public card data`);
      assertPublic(item, `${path}.${key}`);
    });
  }
}

export function callableCards(cards) {
  return cards.filter((card) => card.releaseState === \"active\");
}

export function validateCards(cards) {
  assert(Array.isArray(cards), \"cards must be an array\");
  cards.forEach((card, index) => {
    const path = `cards[${index}]`;
    assert(card && typeof card === \"object\", `${path} must be an object`);
    assert(/^[a-z][a-z0-9-]*$/.test(card.id), `${path}.id must be a stable lowercase slug`);
    assert([\"pending\", \"active\"].includes(card.releaseState), `${path}.releaseState is invalid`);
    DISPLAY_FIELDS.forEach((field) => assert(typeof card[field] === \"string\" && card[field].trim(), `${path}.${field} is required`));
    assert(Array.isArray(card.langs) && card.langs.length, `${path}.langs is required`);
    card.langs.forEach((lang) => assert(SUPPORTED_LANGUAGES.has(lang), `${path}.langs contains an unsupported language`));
    assertPublic(card, path);
  });
  return cards;
}

function assertCallableFixture() {
  const shared = {
    brand: \"Fixture\", agentName: \"Ava\", role: \"Information Assistant\", location: \"Online\",
    description: \"Answers approved questions.\", images: [], trainedOn: [], langs: [\"en\"],
    callLabel: \"Call Fixture\", askHint: \"approved questions\", steps: [],
  };
  const fixture = [
    { ...shared, id: \"pending-agent\", releaseState: \"pending\" },
    { ...shared, id: \"active-agent\", releaseState: \"active\" },
  ];
  validateCards(fixture);
  assert(callableCards(fixture).map((card) => card.id).join(\",\") === \"active-agent\", \"only active cards are callable\");
}

validateCards(SMARTPBX_AGENT_CARDS);
assertCallableFixture();
const bookDemo = readFileSync(new URL(\"../components/pages/BookDemo.tsx\", import.meta.url), \"utf8\");
assert(bookDemo.includes('SMARTPBX_AGENT_CARDS.filter((card) => card.releaseState === "active")'), \"BookDemo must filter active cards\");
"""


def _update_package(path: Path) -> bool:
    package = json.loads(path.read_text(encoding="utf-8"))
    scripts = package.get("scripts")
    if not isinstance(scripts, dict):
        raise ValueError("website package.json must contain a scripts object")
    command = "node scripts/validate-smartpbx-card.mjs"
    existing = scripts.get("test:smartpbx")
    if existing is not None and existing != command:
        raise ValueError("website package.json already has an incompatible test:smartpbx command")
    if existing == command:
        return False
    scripts["test:smartpbx"] = command
    path.write_text(json.dumps(package, ensure_ascii=True, indent=2) + "\n", encoding="utf-8")
    return True


def render_website_artifacts(
    manifest: AgentManifest,
    resources: DerivedResources,
    *,
    backend_artifact_digest: str,
    backend_branch_sha: str,
    output_dir: Path,
) -> WebsiteRenderReport:
    """Write review-only website artifacts into an isolated website worktree."""
    dependency = _validate_dependency(
        backend_artifact_digest=backend_artifact_digest,
        backend_branch_sha=backend_branch_sha,
    )
    output_dir = Path(output_dir)
    page_path = output_dir / "components" / "pages" / "BookDemo.tsx"
    package_path = output_dir / "package.json"
    if not page_path.is_file() or not package_path.is_file():
        raise ValueError("output_dir must be an isolated website worktree with BookDemo.tsx and package.json")

    card = _card(manifest, resources)
    data_path = output_dir / "data" / "smartpbx-agents.generated.mjs"
    validator_path = output_dir / "scripts" / "validate-smartpbx-card.mjs"
    data_path.parent.mkdir(parents=True, exist_ok=True)
    validator_path.parent.mkdir(parents=True, exist_ok=True)
    data_path.write_text(_render_cards_module(card, dependency), encoding="utf-8")
    validator_path.write_text(_validator_source(), encoding="utf-8")

    page_source, page_changed = _integrate_book_demo(page_path.read_text(encoding="utf-8"))
    if page_changed:
        page_path.write_text(page_source, encoding="utf-8")
    _update_package(package_path)

    return WebsiteRenderReport(
        dependency=dependency,
        card_ids=(manifest.slug,),
        output_paths=(
            Path("data/smartpbx-agents.generated.mjs"),
            Path("scripts/validate-smartpbx-card.mjs"),
            Path("components/pages/BookDemo.tsx"),
            Path("package.json"),
        ),
    )
